
app = "mortar-studio-express"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  NODE_ENV = "production"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "npm run build"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[checks]
  [checks.health]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"


