# fly.toml app configuration file generated for mortar-studio-express-spxfia on 2025-08-03T21:27:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mortar-studio-express-spxfia'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
